import Head from "next/head";
import styles from "../styles/Home.module.css";

import PromptForm from "../components/PromptForm";
import AnswerSection from "../components/AnswerSection";

import { Container, Title, Text } from "@mantine/core";
import { useState } from "react";

const text_resp =
  "Here is an example of creating a sphere in Three.js:\n" +
  "\n" +
  "```javascript\n" +
  "// Create a sphere geometry\n" +
  "var geometry = new THREE.SphereGeometry( 5, 32, 32 );\n" +
  "\n" +
  "// Create a material\n" +
  "var material = new THREE.MeshBasicMaterial( {color: 0xffff00} );\n" +
  "\n" +
  "// Create a mesh using the geometry and material\n" +
  "var sphere = new THREE.Mesh( geometry, material );\n" +
  "\n" +
  "// Add the sphere to the scene\n" +
  "scene.add( sphere );\n" +
  "```\n" +
  "\n" +
  "In this example, we use the `THREE.SphereGeometry` class to create a sphere geometry with a radius of 5, 32 horizontal segments, and 32 vertical segments. We then use the `THREE.MeshBasicMaterial` class to create a yellow material for the sphere. Finally, we create a `THREE.Mesh` object using the geometry and material, and add it to the scene.";

function formatResponse(response) {
  // response = response.replace(" ", " ----");
  return response;
}

export default function Home() {
  const [processing, setProcessing] = useState(false);
  const [storedValues, setStoredValues] = useState([
    {
      question: "Hello!",
      answer: formatResponse(text_resp),
    },
    {
      question: "Hello!",
      answer: formatResponse(text_resp),
    },
    {
      question: "Hello!",
      answer: formatResponse(text_resp),
    },
  ]);

  async function generateResponse(prompt, setPrompt) {
    setProcessing(true);

    const response = await fetch("/api/ask", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt: prompt }),
    });

    const json = await response.json();
    if (json.error !== null) {
      console.error(json.error);
      setProcessing(false);
    } else {
      console.log(json);
      setStoredValues([
        ...storedValues,
        {
          question: prompt,
          answer: json.answer,
        }
        
      ]);
      setPrompt("");
      setProcessing(false);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={styles.main}>
        <Container className={styles.header}>
          <Title color="orange" className={styles.title}>Sokaris ChatGPT 🤖</Title>
          {storedValues.length < 1 && (
            <Text>
              I am an automated question and answer system, designed to assist
              you in finding relevant information. You are welcome to ask me any
              queries you may have, and I will do my utmost to offer you a
              reliable response. Kindly keep in mind that I am a machine and
              operate solely based on programmed algorithms.
            </Text>
          )}
        </Container>
        <Container className={styles.chat_main}>
          {storedValues.length > 0 && (
            <AnswerSection storedValues={storedValues} />
          )}
          <PromptForm
            processing={processing}
            generateResponse={generateResponse}
          />
        </Container>
      </Container>
    </>
  );
}
